erp_admin:
    resource: "@ERPAdminBundle/Controller/"
    type:     annotation
    prefix:   /

erp_rrhh:
    resource: "@ERPRrhhBundle/Controller/"
    type:     annotation
    prefix:   /

erpcrm:
    resource: "@ERPCRMBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
